### ISSUE TITLE
Plugin not-reopening site?

### ISSUE THREAD

**Issue by krionical** [amiad/wp-shamor#1]
Plugin counted down to Shabbat, then displayed the following which is also on wpshamor.com:

![shamor](https://github.com/amiad/wp-shamor/assets/20403484/2a303d38-3131-4464-9d52-90463520794c)

Is this the expected behavior?

**Comment by amiad** [comment]
no, the site should open after Shabbath.

What your site?

**Comment by krionical** [comment]
I had to adopt a manual solution as other Sabbaths were happening before you answered. I am going to mark this as closed, but there was an error at the rollover of the new year.
